### ISSUE TITLE
[Feed] DB to Front feed에서 load 후 보여줄 때 거리순 + 시간순 가중치 알고리즘 구현

### ISSUE THREAD

**Issue by jeiljeong** [gkdis6/zagook#13]
어떤 방식으로 불러올까요? 날짜, 거리? 어떤 기준으로? 일반적으로 시간을 기준으로 정렬, 거리를 기준으로 정렬 할 수 있음. 그럴 경우 현재 올라올 정보는 너무 과거일 수도 있음, 일반적으로 우리는 과거보다는 시간 순으로 구경하고 싶음, 최대값을 줘야함, 가중치를 계산해서 가져올 수 있는 알고리즘 구현이 필요

**Comment by gkdis6** [comment]
저는 거리순이 더 먼저인 것 같아요. 지도라는 특성이 있기도 하고 제가 이 프로그램을 사용한다고 생각한다면  자주 사용할 상황이 여행을 왔는데 아무것도 찾아보지 않았거나 혹은 갈려고 했던 곳을 가지 못하는 상황이 되어서 주변에 다른 괜찮은 곳이 있나 찾아볼 때 혹은 일상행활을 하다가 주변에 어디 갈 곳이 있나 사진 잘 나오는 곳이 있나 하고 찾아볼 때 사용할 것 같습니다. 그래서 처음 이 프로그램을 켰을 때 거리순으로 정렬되어 너무 오래된 사진이 나오면 당연히 별로일 수도 있겠지만 반대로 예전엔 이랬구나 할수도 있고 이게 다른 sns 서비스와의 차별점이 될거라고 생각합니다. 최신 맛집, 유행하는 장소 다 좋지만 그런 곳들은 유행하는 시기에 사람이 몰려서 사람이 너무 많고 잠시 반짝하고 묻히기 때문에 사람들이 꾸준히 찾아보고 갈 수 있는 sns를 만들고 싶네요.
